name: Upload Release Files

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload EXE file
        uses: softprops/action-gh-release@v2
        with:
          files: |
            GoogleDorkingTool-v*.exe
            GoogleDorkingTool_v*.zip
